pipeline {
    agent any

    environment {
        MAVEN_HOME = '/usr/share/maven'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/HariMedarametla1243/RestAPI-with-Mysql-with-JPA-Demo.git'
            }
        }

        stage('Build') {
            agent { docker { image 'maven:3.8.5-openjdk-17' } }
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            agent { docker { image 'maven:3.8.5-openjdk-17' } }
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        sh '''
                            docker build -t $DOCKER_USER/my-springboot-app .
                            docker tag $DOCKER_USER/my-springboot-app $DOCKER_USER/my-springboot-app:latest
                            docker push $DOCKER_USER/my-springboot-app:latest
                        '''
                    }
                }
            }
        }
    }
}
